version: "3.3"

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    env_file: .env
    container_name: wordpress
